package com.acquirerx.backend.dispute.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

import java.time.LocalDateTime;

/**
 * Data Transfer Object (DTO) for Dispute Document.
 * Represents the evidence (receipts, invoices, etc.) attached to a dispute.
 * Used to safely transfer document links and metadata between the frontend and backend.
 */
public class DisputeDocumentDTO {

    // Auto-generated by the database, so not required when creating
    private Integer docId;

    // -------------------------------------------------------------------------
    // VALIDATION RULES
    // -------------------------------------------------------------------------

    // We only need the Case ID to link this document, not the whole Case object!
    @NotNull(message = "Case ID is required to upload a document")
    private Integer caseId;

    @NotBlank(message = "Document type must be specified (e.g., Receipt, Invoice, Proof)")
    private String docType;

    @NotBlank(message = "Document URI (file path/link) cannot be empty")
    private String uri;

    // Usually set by the backend when the file is uploaded, but included here
    // so the frontend can display when the evidence was submitted.
    private LocalDateTime uploadedDate;

    public DisputeDocumentDTO() {
    }

    public DisputeDocumentDTO(Integer docId, Integer caseId, String docType, String uri, LocalDateTime uploadedDate) {
        this.docId = docId;
        this.caseId = caseId;
        this.docType = docType;
        this.uri = uri;
        this.uploadedDate = uploadedDate;
    }

    public Integer getDocId() {
        return docId;
    }

    public void setDocId(Integer docId) {
        this.docId = docId;
    }

    public Integer getCaseId() {
        return caseId;
    }

    public void setCaseId(Integer caseId) {
        this.caseId = caseId;
    }

    public String getDocType() {
        return docType;
    }

    public void setDocType(String docType) {
        this.docType = docType;
    }

    public String getUri() {
        return uri;
    }

    public void setUri(String uri) {
        this.uri = uri;
    }

    public LocalDateTime getUploadedDate() {
        return uploadedDate;
    }

    public void setUploadedDate(LocalDateTime uploadedDate) {
        this.uploadedDate = uploadedDate;
    }
}