package com.acquirerx.backend.dispute.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.time.LocalDateTime;

/**
 * Data Transfer Object (DTO) for Dispute Action.
 * Represents a single event or audit log entry in a dispute's lifecycle.
 * We use this to capture incoming requests (like an analyst adding a note)
 * and to send the case history back to the frontend.
 */
public class DisputeActionDTO {

    // Auto-generated by the database, so we don't force the frontend to send this
    private Integer actionId;

    // -------------------------------------------------------------------------
    // VALIDATION RULES
    // -------------------------------------------------------------------------

    // We only need the Case ID, not the entire DisputeCase object!
    // This keeps the JSON payload small and prevents infinite loops.
    @NotNull(message = "Case ID is required to log an action")
    private Integer caseId;

    @NotBlank(message = "Action type cannot be blank (e.g., RequestDocs, Accept, Reject)")
    private String actionType;

    @NotNull(message = "Actor ID is required to track who performed this action")
    private Integer actorId;

    // Usually generated by the server to prevent users from faking timestamps,
    // but included here so we can send the exact time back to the frontend.
    private LocalDateTime actionDate;

    // Optional field, but if they provide notes, we restrict the length to match our database column
    @Size(max = 1000, message = "Notes cannot exceed 1000 characters")
    private String notes;

    public DisputeActionDTO() {
    }

    public DisputeActionDTO(Integer actionId, Integer caseId, String actionType, Integer actorId, LocalDateTime actionDate, String notes) {
        this.actionId = actionId;
        this.caseId = caseId;
        this.actionType = actionType;
        this.actorId = actorId;
        this.actionDate = actionDate;
        this.notes = notes;
    }

    public Integer getActionId() {
        return actionId;
    }

    public void setActionId(Integer actionId) {
        this.actionId = actionId;
    }

    public Integer getCaseId() {
        return caseId;
    }

    public void setCaseId(Integer caseId) {
        this.caseId = caseId;
    }

    public String getActionType() {
        return actionType;
    }

    public void setActionType(String actionType) {
        this.actionType = actionType;
    }

    public Integer getActorId() {
        return actorId;
    }

    public void setActorId(Integer actorId) {
        this.actorId = actorId;
    }

    public LocalDateTime getActionDate() {
        return actionDate;
    }

    public void setActionDate(LocalDateTime actionDate) {
        this.actionDate = actionDate;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }
}